language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'

before_script:
    - composer install

script: vendor/phpunit/phpunit/phpunit

after_script:
    - vendor/bin/coveralls -v

notifications:
    on_success: never
    on_failure: always
